======================================================================
ERROR: test_requests (test_requests.TestRequests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chefe02/Desktop/presales_cert/Artifacts/2018-10-23_10-31-01.708986bz/test_requests.py", line 63, in test_requests
    self.driver.find_element(By.LINK_TEXT, _tpl.apply(u'Accessories')).click()
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Accessories"}
  (Session info: chrome=70.0.3538.67)
  (Driver info: chromedriver=2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363),platform=Mac OS X 10.13.6 x86_64)


----------------------------------------------------------------------
Ran 1 test in 67.896s

FAILED (errors=1)
