======================================================================
ERROR: test_requests (NOP_SC3.NOPCommerceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chefe02/Desktop/presales_cert/NOP_SC3.py", line 72, in test_requests
    self.driver.find_element(By.LINK_TEXT, _tpl.apply(u'Apparel')).click()
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Element <a href="/nopCommerce/apparel">...</a> is not clickable at point (474, 15). Other element would receive the click: <p class="content">...</p>
  (Session info: chrome=70.0.3538.77)
  (Driver info: chromedriver=2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363),platform=Mac OS X 10.13.6 x86_64)


----------------------------------------------------------------------
Ran 1 test in 29.064s

FAILED (errors=1)
======================================================================
ERROR: test_requests (NOP_SC3.NOPCommerceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chefe02/Desktop/presales_cert/NOP_SC3.py", line 72, in test_requests
    self.driver.find_element(By.LINK_TEXT, _tpl.apply(u'Apparel')).click()
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Element <a href="/nopCommerce/apparel">...</a> is not clickable at point (474, 15). Other element would receive the click: <p class="content">...</p>
  (Session info: chrome=70.0.3538.77)
  (Driver info: chromedriver=2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363),platform=Mac OS X 10.13.6 x86_64)


----------------------------------------------------------------------
Ran 1 test in 28.509s

FAILED (errors=1)
======================================================================
ERROR: test_requests (NOP_SC3.NOPCommerceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chefe02/Desktop/presales_cert/NOP_SC3.py", line 72, in test_requests
    self.driver.find_element(By.LINK_TEXT, _tpl.apply(u'Apparel')).click()
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Element <a href="/nopCommerce/apparel">...</a> is not clickable at point (474, 15). Other element would receive the click: <p class="content">...</p>
  (Session info: chrome=70.0.3538.77)
  (Driver info: chromedriver=2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363),platform=Mac OS X 10.13.6 x86_64)


----------------------------------------------------------------------
Ran 1 test in 28.933s

FAILED (errors=1)
======================================================================
ERROR: test_requests (NOP_SC3.NOPCommerceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chefe02/Desktop/presales_cert/NOP_SC3.py", line 72, in test_requests
    self.driver.find_element(By.LINK_TEXT, _tpl.apply(u'Apparel')).click()
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/Cellar/bzt/1.13.0/libexec/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Element <a href="/nopCommerce/apparel">...</a> is not clickable at point (474, 15). Other element would receive the click: <p class="content">...</p>
  (Session info: chrome=70.0.3538.77)
  (Driver info: chromedriver=2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363),platform=Mac OS X 10.13.6 x86_64)


----------------------------------------------------------------------
Ran 1 test in 28.111s

FAILED (errors=1)
